### PR TITLE
Clean up and unite parallel and sequential version

### LINKED ISSUE #8: Get rid of some of the main* files
I guess a fully parallel and a fully sequential version would be enough. One probably doesn't even need two different files / functions for that.

There is some global variable in HPCGAP that one can check to differentiate HPCGAP from GAP. I think it's called something like `IsHPCGAP`?

### PR DESCRIPTION
**Pull request by emmakatherina**
Fixes #8 and #38 by uniting the sequential and the parallel version and deleting the semi parallel versions.

Please review. Please merge.

### CODE REVIEW

**Comment by ssiccha** [comment]
Basically the sequential version could also use `ScheduleTask` and `WaitTask`. The only difference would be that `ScheduleTask` in GAP would just call the function immediately and `WaitTask` would just be `WaitTask := function() return; end;`.

**Comment by emmakatherina** [comment]
I looked into that and added those two functions to lib/hpc/tasks.g in my local gap repo:
```
ScheduleScheduleTask := function(cond, func, args...)                                                            
    local result;
    result := CallFuncListWrap(func, args);
    if result = [] then
        return rec(taskresult := fail);
    else
        return rec(taskresult := result[1]);
    fi; 
end;

WaitTask := function(args...)
    return;
end;
```
They are quite similar to the function RunTask that already existed. With those two functions I was able to execute the tests for the sequential and the parallel version without any errors!

**Comment by emmakatherina** [comment]
I could try to make a pull request to gap-system/gap now, but I am not sure about the conventions. If there is anyone available I would like to learn it, though.

**Comment by ssiccha** [comment]
For `ScheduleTask` you can also do
```
ScheduleTask := function(cond, func, args...)                                                            
    return RunTask(func, args)
end;
```
You get less code duplication this way.

**Comment by ssiccha** [comment]
It would be great if you submit this to the gap-system/gap repository. Maybe add a few trivial tests to `tst/testinstall/hpc/task.tst` for the sake of completeness. Make sure that you have a good commit message (you can send it to me beforehand). Then you can open the PR directly and don't need to add anything else.

**Comment by ssiccha** [comment]
This has a few conflicts with the last change you did in `measure_contention.g`.

**Pull request merged**
