### PR TITLE
Broaden use of GAUSS_randomEchelonMat in tests - obsolete

### LINKED ISSUE #62: Use RandomEchelonMat in tests more

### PR DESCRIPTION
**Pull request by emmakatherina**
Adds the test files tst/parallel/special_matrices.tst and tst/standard/special_matrices.tst where tests for special matrices are executed. Those special matrices are stored in tst/testdata/matrices.g and there is a new file tst/testfunctions.g for functions that are for usage in tests only.

Fixes #62, please merge.

Note: I reopened this PR after spending a lot of time rebasing it, because I was hoping that the number of new commits would not increase like it does right now.
While rebasing and merging with the current master, I amended the changes to the original commit "Broaden ..." which was from the end of september. That leaded to a couple of merge conflicts which I resolved. This is why there are so many "new" commits now.
Maybe those commits are going to be shown twice now - unfortunately I really don't know how to solve this. I spent a lot of time trying to solve this...

### CODE REVIEW

**Comment by ssiccha** [comment]
I managed to salvage this by doing
```
git co master
git co -b randomEchelonMat_tests_62_copy
git cherry-pick 7dc697f
```
Note that `7dc697f` is the short commit hash of `Broaden use of GAUSS_randomEchelonMat in tests`.

**Comment by ssiccha** [comment]
The commit itself LGTM.
Two minor nitpicks:
- Please add a 1x1 zero rank, and a 1x1 full rank matrix. Also I think our matrices do not _need_ to be square matrices. If the algorithm works with non-square matrices please also add a 1xn, an nx1, and e.g. a 200x50 matrix.
- I guess this is more a matter of taste: why do you add artificial entries to `M_q` etc. to handle the `M_no` "matrix"? I would just do `DoEchelonMatTransformationBlockwise(3, GF(2), true, 2, 2);` in the test-files.

**Comment by emmakatherina** [comment]
Testing the algorithm with a simple example of a non-square matrix I received the following error message:
```
gap> DoEchelonMatTransformation(RandomEchelonMat(1, 100, 1, randomSource, GF(5)), GF(5), true, 1, 100);
Error, Variable: 'DoEchelonMatTransformation' must have a value
not in any function at stream:23
gap> DoEchelonMatTransformationBlockwise(RandomEchelonMat(1, 100, 1, randomSource, GF(5)), GF(5), true, 1, 100);
Error, List Element: <list>[2] must have an assigned value in
   called from 
you can 'return;' after assigning a value
TaskListUpdateM[i][j][h] := ScheduleTask( UpdateRowTrafoInput[1], GAUSS_UpdateRowTrafo, UpdateRowTrafoInput[2], 
   UpdateRowTrafoInput[3], UpdateRowTrafoInput[4], UpdateRowTrafoInput[5], UpdateRowTrafoInput[6], 
   UpdateRowTrafoInput[7], UpdateRowTrafoInput[8], UpdateRowTrafoInput[9] )
 ; at /home/emma/Source/hpcgap/pkg/GaussPar/gap/main.g:271Chief( galoisField, mat, numberChopsHeight, numberChopsWidth, IsHPC 
 ) at /home/emma/Source/hpcgap/pkg/GaussPar/gap/main.gi:46 called from
<function "DoEchelonMatTransformationBlockwise">( <arguments> )
 called from read-eval loop at stream:24
brk> 
```

**Comment by ssiccha** [comment]
Superseded by #99 and #100.

**Pull request closed without merging**
