### PR TITLE
Verify output via transformation matric in Chief function

### LINKED ISSUE #54: Add function to verify output via transformation matrix
If a transformation matrix was computed one could check the computation by applying the transformation matrix and checking whether the result is in row reduced echelon form.

One could pass a `verify := true` option to our main function which runs the verification after the algorithm itself. This would very comfortably increase the trustworthiness of our results a lot. HPC-GAP is still alpha. Even it weren't this is still a multi-threaded program.

### PR DESCRIPTION
**Pull request by emmakatherina**
Checks whether the result, that you get through applying the transformation
matrix to the matrix is, is in RREF. If not than the algorithm is not correct
and an alert is given.

Fixes #54 .

Enhancement: We could add a new parameter to make the verification optional. That would make the function signature longer. The function IsMatrixInRREF's runtime is in O(n^2) where n is the dimension of the matrix. I don't know if this carries weight compared to the runtime of the main algorithm.

Please review.

### CODE REVIEW

**Comment by emmakatherina** [comment]
I also think that the first option is better. Hopefully it's fine that I used your mail address - I didn't think mine or Jendrik's would make a lot of sense.

Unfortunately I failed when I tried to squash the merge commit which was necessary because of merge conflicts. git rebase didn't work for me. Do you have another suggestion or can we just keep this commit?

**Comment by ssiccha** [comment]
No worries about the conflicts. I'll take care of it. :+1:

**Comment by ssiccha** [comment]
I should have been a bit clearer, but I wrote my comment in a hurry.  :) I meant use `Error` instead of `Info`. Also, with the merge commit I think this partially undoes 4a5f9b0. I'll take care of this when I cherry-pick this into a new branch.

**Comment by ssiccha** [comment]
This is picked up in #179.

**Pull request closed without merging**
